# Generated by Django 4.0 on 2022-01-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='room',
        ),
    ]
